// Generated file. Do not edit.
//
// Source: vercel-labs/vgpu @ bd3b05101fdd1193a1593558d3c52a0b2b18f31d
// Entry:  apps/docs/app/[lang]/(home)/components/prism-background/bloom-upsample.wgsl
// Modules resolved into this shader:
//   apps/docs/app/[lang]/(home)/components/prism-background/bloom-upsample.wgsl  sha256:be8e461a8fef0b0e81fe594b83f8abb9afa399b65be9b5c2163d7d8b5a17757f
// Method: @vgpu/wgsl 0.3.1 resolveShader(), with the same identifier-preserving
//   options the upstream bundler loader is configured with, then module paths rewritten
//   to the stable identities above. Resolution happens here, once, not in the browser.
export default {version: 1, wgsl: "// vgsl-module: apps/docs/app/[lang]/(home)/components/prism-background/bloom-upsample.wgsl\n// One additive step of the bloom reconstruction chain.\n//\n// The source is the next-smaller pyramid level. Its filtered contribution is\n// blended over the preserved destination, so updated energy travels from\n// 1/16 -> 1/8 -> 1/4 -> 1/2 without another ping-pong texture.\n\nstruct _vgsl_db6760c4__UpsampleParams {\n  sourceTexelSize: vec2f,\n  radius: f32,\n  scatter: f32,\n}\n\n@group(0) @binding(0) var sourceTexture: texture_2d<f32>;\n@group(0) @binding(1) var sourceSampler: sampler;\n@group(0) @binding(2) var<uniform> params: _vgsl_db6760c4__UpsampleParams;\n\nconst _vgsl_db6760c4__TAU = 6.28318530718;\n\nfn _vgsl_db6760c4__hash12(pixel: vec2f) -> f32 {\n  let p = fract(pixel * vec2f(0.1031, 0.1030));\n  let mixed = p + dot(p, p.yx + vec2f(33.33));\n  return fract((mixed.x + mixed.y) * mixed.x);\n}\n\n@fragment\nfn fs_main(\n  @location(0) uv: vec2f,\n  @builtin(position) position: vec4f,\n) -> @location(0) vec4f {\n  let rotation = _vgsl_db6760c4__hash12(floor(position.xy) + vec2f(19.0, 73.0)) * _vgsl_db6760c4__TAU;\n  let radius = max(params.radius, 0.0);\n  var color = textureSampleLevel(sourceTexture, sourceSampler, uv, 0.0).rgb * 0.25;\n  for (var tap = 0; tap < 6; tap = tap + 1) {\n    let angle = rotation + f32(tap) * (_vgsl_db6760c4__TAU / 6.0);\n    let offset = vec2f(cos(angle), sin(angle)) * params.sourceTexelSize * radius;\n    color += textureSampleLevel(sourceTexture, sourceSampler, uv + offset, 0.0).rgb\n      * 0.125;\n  }\n  return vec4f(color * max(params.scatter, 0.0), 0.0);\n}\n"} as const
