// Generated file. Do not edit.
//
// Source: vercel-labs/vgpu @ bd3b05101fdd1193a1593558d3c52a0b2b18f31d
// Entry:  apps/docs/app/[lang]/(home)/components/prism-background/bloom.wgsl
// Modules resolved into this shader:
//   apps/docs/app/[lang]/(home)/components/prism-background/bloom.wgsl  sha256:ce9ea1295366575c161b7b741fe65bb469585e9e939b03a1b985e5110928fe68
// Method: @vgpu/wgsl 0.3.1 resolveShader(), with the same identifier-preserving
//   options the upstream bundler loader is configured with, then module paths rewritten
//   to the stable identities above. Resolution happens here, once, not in the browser.
export default {version: 1, wgsl: "// vgsl-module: apps/docs/app/[lang]/(home)/components/prism-background/bloom.wgsl\n// One level of an Unreal-style bloom pyramid.\n//\n// Every pass renders at half the resolution of its source. A rotated 9-tap\n// kernel performs a smooth low-pass while downsampling; a stable screen-space\n// hash changes the rotation per output texel so parallel light edges do not\n// reveal a regular sampling grid. Only the first level extracts highlights.\n\nstruct _vgsl_b0bfaace__BloomParams {\n  sourceTexelSize: vec2f,\n  threshold: f32,\n  extractHighlights: f32,\n}\n\n@group(0) @binding(0) var sourceTexture: texture_2d<f32>;\n@group(0) @binding(1) var sourceSampler: sampler;\n@group(0) @binding(2) var<uniform> params: _vgsl_b0bfaace__BloomParams;\n\nconst _vgsl_b0bfaace__TAU = 6.28318530718;\n\nfn _vgsl_b0bfaace__hash12(pixel: vec2f) -> f32 {\n  let p = fract(pixel * vec2f(0.1031, 0.1030));\n  let mixed = p + dot(p, p.yx + vec2f(33.33));\n  return fract((mixed.x + mixed.y) * mixed.x);\n}\n\nfn _vgsl_b0bfaace__lowPass(uv: vec2f, outputPixel: vec2f) -> vec3f {\n  let rotation = _vgsl_b0bfaace__hash12(outputPixel) * _vgsl_b0bfaace__TAU;\n  var result = textureSampleLevel(sourceTexture, sourceSampler, uv, 0.0).rgb * 0.25;\n  for (var tap = 0; tap < 8; tap = tap + 1) {\n    let angle = rotation + f32(tap) * (_vgsl_b0bfaace__TAU / 8.0);\n    let offset = vec2f(cos(angle), sin(angle)) * params.sourceTexelSize * 1.5;\n    result += textureSampleLevel(sourceTexture, sourceSampler, uv + offset, 0.0).rgb\n      * 0.09375;\n  }\n  return max(result, vec3f(0.0));\n}\n\n/** Soft-knee extraction keeps the edge around the HDR threshold continuous. */\nfn _vgsl_b0bfaace__brightContribution(color: vec3f) -> vec3f {\n  let brightness = max(max(color.r, color.g), color.b);\n  let threshold = max(params.threshold, 0.0);\n  let knee = max(threshold * 0.5, 0.0001);\n  var soft = clamp(brightness - threshold + knee, 0.0, 2.0 * knee);\n  soft = soft * soft / (4.0 * knee + 0.0001);\n  let contribution = max(brightness - threshold, soft) / max(brightness, 0.0001);\n  return color * contribution;\n}\n\n@fragment\nfn fs_main(@location(0) uv: vec2f, @builtin(position) position: vec4f) -> @location(0) vec4f {\n  let filtered = _vgsl_b0bfaace__lowPass(uv, floor(position.xy));\n  let color = select(filtered, _vgsl_b0bfaace__brightContribution(filtered), params.extractHighlights > 0.5);\n  return vec4f(color, 1.0);\n}\n"} as const
