// Generated file. Do not edit.
//
// Source: vercel-labs/vgpu @ bd3b05101fdd1193a1593558d3c52a0b2b18f31d
// Entry:  apps/docs/app/[lang]/(home)/components/prism-background/present.wgsl
// Modules resolved into this shader:
//   @vgpu/wgsl-std/src/color/index.wgsl  sha256:9a65713c22469c7aea102286385e00d5ac8c5986bb415384af779c04fbf88401
//   apps/docs/app/[lang]/(home)/components/prism-background/present.wgsl  sha256:9bc3bc44d668b1da8df1879b02942d202caa98fc040293072de61c192ab68dc4
// Method: @vgpu/wgsl 0.3.1 resolveShader(), with the same identifier-preserving
//   options the upstream bundler loader is configured with, then module paths rewritten
//   to the stable identities above. Resolution happens here, once, not in the browser.
export default {version: 1, wgsl: "// vgsl-module: apps/docs/app/[lang]/(home)/components/prism-background/present.wgsl\n// Final linear-HDR presentation. The bloom pyramid is already rebuilt\n// additively from 1/16 back to 1/2 resolution, so this pass only normalizes the\n// accumulated energy, adds it to the untouched HDR scene, and performs the one\n// ACES tone mapping plus sRGB conversion.\n\n      \n\n@group(0) @binding(0) var sceneTexture: texture_2d<f32>;\n@group(0) @binding(1) var bloomTexture: texture_2d<f32>;\n@group(0) @binding(2) var bloomSampler: sampler;\n\nstruct _vgsl_cb7fa732__PresentParams {\n  bloomStrength: f32,\n}\n\n@group(0) @binding(3) var<uniform> params: _vgsl_cb7fa732__PresentParams;\n\n// scatter = 0.65 at all three upsample steps. This is the reciprocal of\n// 1 + scatter + scatter^2 + scatter^3, keeping brightness stable as levels are\n// added while their progressively wider footprints shape the halo.\nconst _vgsl_cb7fa732__BLOOM_ENERGY_NORMALIZATION = 0.426394;\n\n@fragment\nfn fs_main(\n  @location(0) uv: vec2f,\n  @builtin(position) position: vec4f,\n) -> @location(0) vec4f {\n  let scene = textureLoad(sceneTexture, vec2i(position.xy), 0).rgb;\n  let bloom = textureSampleLevel(bloomTexture, bloomSampler, uv, 0.0).rgb\n    * _vgsl_cb7fa732__BLOOM_ENERGY_NORMALIZATION;\n  let linear = max(scene + bloom * max(params.bloomStrength, 0.0), vec3f(0.0));\n  return vec4f(_vgsl_4c2c8948__linearToSrgb3(_vgsl_4c2c8948__tonemapAces(linear)), 1.0);\n}\n\n// vgsl-module: @vgpu/wgsl-std/src/color/index.wgsl\n\n\n\n\n\n\n\n\n\n\nfn _vgsl_4c2c8948__linearToSrgb(value: f32) -> f32 {\n  if (value <= 0.0031308) {\n    return value * 12.92;\n  }\n  return 1.055 * pow(value, 1.0 / 2.4) - 0.055;\n}\n\nfn _vgsl_4c2c8948__linearToSrgb3(value: vec3f) -> vec3f {\n  return vec3f(_vgsl_4c2c8948__linearToSrgb(value.r), _vgsl_4c2c8948__linearToSrgb(value.g), _vgsl_4c2c8948__linearToSrgb(value.b));\n}\n\n\n\nfn _vgsl_4c2c8948__tonemapAces(value: vec3f) -> vec3f {\n  let a = 2.51;\n  let b = 0.03;\n  let c = 2.43;\n  let d = 0.59;\n  let e = 0.14;\n  return clamp((value * (a * value + b)) / (value * (c * value + d) + e), vec3f(0.0), vec3f(1.0));\n}\n\n\n\n\n"} as const
