defmodule TechtreeWeb.ExactResponse do
  @moduledoc """
  Sending bytes this application did not produce, and failing honestly when it
  cannot.

  Three endpoints return generated bytes verbatim, and all three owe the caller
  the same things: the media type the catalog recorded, an entity tag that is
  the digest those bytes hash to, a caching rule that matches how immutable the
  address is, and a `304` when the caller already holds that exact digest. That
  is one rule, so it lives in one place rather than three times over.

  Failures use the spec section 15 error vocabulary: a stable code, a message
  that is safe to show a stranger, and whether retrying could help. Nothing else
  — a catalog failure must not describe the serving host.
  """

  import Plug.Conn

  alias Techtree.Catalog.Error

  # A content address cannot change meaning, so a client may keep it forever.
  @immutable "public, max-age=31536000, immutable"

  # The catalog index and the bootstrap release change between releases, so they
  # are cached briefly and revalidated with their digest.
  @revalidated "public, max-age=300"

  @typedoc """
  How long a caller may keep the bytes: `:immutable` for content addresses,
  `:revalidated` for the documents a release replaces.
  """
  @type caching :: :immutable | :revalidated

  @doc """
  Send exact bytes, or a `304` if the caller already holds this digest.
  """
  @spec send_exact(Plug.Conn.t(), binary(), String.t(), String.t(), caching()) :: Plug.Conn.t()
  def send_exact(conn, bytes, media_type, digest, caching) do
    etag = ~s("#{digest}")

    conn =
      conn
      |> put_resp_content_type(media_type, nil)
      |> put_resp_header("etag", etag)
      |> put_resp_header("cache-control", cache_control(caching))

    if holds?(conn, etag) do
      conn
      |> delete_resp_header("content-type")
      |> send_resp(304, "")
    else
      send_resp(conn, 200, bytes)
    end
  end

  @doc """
  Refuse a request in the same shape every endpoint refuses one.
  """
  @spec send_error(Plug.Conn.t(), Error.t()) :: Plug.Conn.t()
  def send_error(conn, %Error{} = error) do
    send_error(conn, status_for(error.code), error.code, error.message, error.retryable?)
  end

  @doc """
  Refuse a request the catalog was never asked about.
  """
  @spec send_error(Plug.Conn.t(), Plug.Conn.status(), atom(), String.t(), boolean()) ::
          Plug.Conn.t()
  def send_error(conn, status, code, message, retryable?) do
    body =
      Jason.encode_to_iodata!(%{
        "error" => %{
          "code" => to_string(code),
          "message" => message,
          "retryable" => retryable?
        }
      })

    conn
    |> put_resp_content_type("application/json")
    |> put_resp_header("cache-control", "no-store")
    |> send_resp(status, body)
  end

  @doc """
  What each catalog failure means over HTTP, as a fixed policy.

  A digest that names nothing is `404`. Anything else is the service being
  unable to serve what it has: no release imported yet, or bytes that no longer
  match the digest they are filed under. Serving those anyway is the one thing
  this application must never do, so it answers `503` and serves nothing.
  """
  @spec status_for(Error.code()) :: Plug.Conn.status()
  def status_for(:catalog_object_missing), do: 404
  def status_for(:catalog_object_digest_mismatch), do: 503
  def status_for(:bootstrap_release_missing), do: 503
  def status_for(:catalog_bundle_invalid), do: 503

  defp cache_control(:immutable), do: @immutable
  defp cache_control(:revalidated), do: @revalidated

  defp holds?(conn, etag) do
    conn
    |> get_req_header("if-none-match")
    |> Enum.flat_map(&String.split(&1, ","))
    |> Enum.map(&String.trim/1)
    |> Enum.any?(&(&1 == etag or &1 == "*"))
  end
end
