defmodule Techtree.Repo.Migrations.AddPublicationMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:network_publication_entries) do
      add :campaign_name, :text
      add :skill_digest, :text
      add :skill_name, :text
      add :skill_github_url, :text
    end
  end

  def down do
    alter table(:network_publication_entries) do
      remove :skill_github_url
      remove :skill_name
      remove :skill_digest
      remove :campaign_name
    end
  end
end
