defmodule Techtree.Repo.Migrations.AddContributorAddressByParticipant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:network_contributor_addresses_by_participant, primary_key: false) do
      add :participant_key_id, :text, null: false, primary_key: true
      add :contributor_address_unverified, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:network_contributor_addresses_by_participant, [:participant_key_id],
             name: "network_contributor_address_participant_key_idx"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :network_contributor_addresses_by_participant,
                     [:participant_key_id],
                     name: "network_contributor_address_participant_key_idx"
                   )

    drop table(:network_contributor_addresses_by_participant)
  end
end
