defmodule Techtree.Repo.Migrations.CreateNetworkResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:network_withdrawals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reason, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :submission_id, :uuid, null: false
    end

    create table(:network_submissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:network_withdrawals) do
      modify :submission_id,
             references(:network_submissions,
               column: :id,
               name: "network_withdrawals_submission_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :nothing
             )
    end

    alter table(:network_submissions) do
      add :sequence, :bigint, null: false
      add :bundle_digest, :text, null: false
      add :run_id, :text, null: false
      add :campaign_spec_digest, :text, null: false
      add :data_policy_digest, :text, null: false
      add :climb_reference, :text, null: false
      add :executor_kind, :text, null: false
      add :executor_key_id, :text, null: false
      add :executor_public_key, :text, null: false
      add :subject_model, :text, null: false
      add :subject_harness, :text, null: false
      add :subject_harness_version, :text, null: false
      add :baseline_mean, :float, null: false
      add :candidate_mean, :float, null: false
      add :absolute_delta, :float, null: false
      add :wins, :bigint, null: false
      add :losses, :bigint, null: false
      add :ties, :bigint, null: false
      add :task_count, :bigint, null: false
      add :decision, :text, null: false
      add :proof_grade, :text, null: false
      add :verification_checks_run, :bigint, null: false
      add :verification_checks_passed, :bigint, null: false
      add :task_deltas, {:array, :map}, null: false, default: []
      add :raw_payload, :binary, null: false
      add :withdrawn_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:network_submissions, [:bundle_digest],
             name: "network_submissions_unique_bundle_digest_index"
           )

    create unique_index(:network_submissions, [:sequence],
             name: "network_submissions_unique_sequence_index"
           )

    create table(:network_contributor_addresses, primary_key: false) do
      add :address, :text, null: false, primary_key: true
      add :submission_count, :bigint, null: false, default: 1
      add :first_seen_at, :utc_datetime_usec, null: false
      add :last_seen_at, :utc_datetime_usec, null: false

      add :submission_id,
          references(:network_submissions,
            column: :id,
            name: "network_contributor_addresses_submission_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :nothing
          ),
          null: false
    end

    execute("""
    CREATE SEQUENCE network_submission_sequence
    """)
  end

  def down do
    execute("""
    DROP SEQUENCE network_submission_sequence
    """)

    drop constraint(
           :network_contributor_addresses,
           "network_contributor_addresses_submission_id_fkey"
         )

    drop table(:network_contributor_addresses)

    drop_if_exists unique_index(:network_submissions, [:sequence],
                     name: "network_submissions_unique_sequence_index"
                   )

    drop_if_exists unique_index(:network_submissions, [:bundle_digest],
                     name: "network_submissions_unique_bundle_digest_index"
                   )

    alter table(:network_submissions) do
      remove :updated_at
      remove :inserted_at
      remove :withdrawn_at
      remove :raw_payload
      remove :task_deltas
      remove :verification_checks_passed
      remove :verification_checks_run
      remove :proof_grade
      remove :decision
      remove :task_count
      remove :ties
      remove :losses
      remove :wins
      remove :absolute_delta
      remove :candidate_mean
      remove :baseline_mean
      remove :subject_harness_version
      remove :subject_harness
      remove :subject_model
      remove :executor_public_key
      remove :executor_key_id
      remove :executor_kind
      remove :climb_reference
      remove :data_policy_digest
      remove :campaign_spec_digest
      remove :run_id
      remove :bundle_digest
      remove :sequence
    end

    drop constraint(:network_withdrawals, "network_withdrawals_submission_id_fkey")

    alter table(:network_withdrawals) do
      modify :submission_id, :uuid
    end

    drop table(:network_submissions)

    drop table(:network_withdrawals)
  end
end
