defmodule Techtree.Repo.Migrations.CreateCatalogResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:catalog_releases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :channel, :text, null: false
      add :catalog_digest, :text, null: false
      add :source_revision, :text, null: false
      add :bootstrap_digest, :text, null: false
      add :import_status, :text, null: false, default: "importing"
      add :imported_at, :utc_datetime_usec
      add :active, :boolean, null: false, default: false
      add :error_summary, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:catalog_releases, [:channel],
             name: "catalog_releases_one_active_release_per_channel_index",
             where: "(active = true)"
           )

    create table(:catalog_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :protocol_digest, :text, null: false
      add :kind, :text, null: false
      add :reference, :text
      add :relative_path, :text, null: false
      add :media_type, :text, null: false
      add :byte_size, :bigint, null: false
      add :source_revision, :text, null: false
      add :active, :boolean, null: false, default: true
      add :title, :text
      add :summary, :text
      add :status, :text
      add :projection, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:catalog_entries, [:kind, :reference],
             name: "catalog_entries_unique_active_reference_per_kind_index",
             where: "(active = true)"
           )

    create unique_index(:catalog_entries, [:protocol_digest],
             name: "catalog_entries_unique_protocol_digest_index"
           )

    create table(:bootstrap_releases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :channel, :text, null: false
      add :schema_version, :text, null: false
      add :raw_payload, :binary, null: false
      add :payload_digest, :text, null: false
      add :cli_version, :text, null: false
      add :plugin_revision, :text, null: false
      add :minimum_hermes_version, :text, null: false
      add :published_at, :utc_datetime_usec, null: false
      add :active, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:bootstrap_releases, [:channel],
             name: "bootstrap_releases_one_active_bootstrap_per_channel_index",
             where: "(active = true)"
           )

    create unique_index(:bootstrap_releases, [:channel, :payload_digest],
             name: "bootstrap_releases_unique_payload_per_channel_index"
           )
  end

  def down do
    drop_if_exists unique_index(:bootstrap_releases, [:channel, :payload_digest],
                     name: "bootstrap_releases_unique_payload_per_channel_index"
                   )

    drop_if_exists unique_index(:bootstrap_releases, [:channel],
                     name: "bootstrap_releases_one_active_bootstrap_per_channel_index"
                   )

    drop table(:bootstrap_releases)

    drop_if_exists unique_index(:catalog_entries, [:protocol_digest],
                     name: "catalog_entries_unique_protocol_digest_index"
                   )

    drop_if_exists unique_index(:catalog_entries, [:kind, :reference],
                     name: "catalog_entries_unique_active_reference_per_kind_index"
                   )

    drop table(:catalog_entries)

    drop_if_exists unique_index(:catalog_releases, [:channel],
                     name: "catalog_releases_one_active_release_per_channel_index"
                   )

    drop table(:catalog_releases)
  end
end
