defmodule Techtree.CanonicalTest do
  @moduledoc """
  Proving, rather than believing, that this encoder is the other one.

  The claim under test is byte equality with `techtree.canonical`, and the only
  evidence worth having for it is the encoder's own output. So the fixture is
  generated by running the Python encoder — `scripts/generate_canonical_fixture.py`
  — over a real proof bundle, over the golden documents that repository tests
  itself against, and over a thousand numbers chosen to sit on every boundary in
  the number rules. Nothing in this file was written by hand from a reading of
  RFC 8785.

  The two halves check different things. The golden documents are
  pretty-printed, so re-encoding them is a real re-encoding: key order,
  whitespace and number spelling all have to be rebuilt. The proof bundle's
  files are already canonical, so re-encoding them has to be the identity —
  which is the property that actually matters in production, because it is the
  one a `payload_digest` depends on.
  """

  use ExUnit.Case, async: true

  alias Techtree.Canonical

  doctest Techtree.Canonical

  @fixtures Path.expand("../support/fixtures", __DIR__)
  @canonical Path.join(@fixtures, "canonical")

  describe "against the Python encoder's own output" do
    test "every golden document re-encodes to exactly the bytes it produced" do
      documents = Path.wildcard(Path.join(@canonical, "documents/*.json"))

      assert length(documents) == 16

      for document <- documents do
        expected =
          @canonical
          |> Path.join("expected/#{Path.basename(document, ".json")}.canonical")
          |> File.read!()

        assert Canonical.encode!(Jason.decode!(File.read!(document))) == expected,
               "#{Path.basename(document)} does not re-encode to the canonical bytes"
      end
    end

    test "every file in a real proof bundle re-encodes to its own bytes" do
      listed =
        @canonical
        |> Path.join("already-canonical.json")
        |> File.read!()
        |> Jason.decode!()

      root = Path.join(@fixtures, "proof")

      present =
        root
        |> Path.join("**/*.json")
        |> Path.wildcard()
        |> Enum.map(&Path.relative_to(&1, root))
        |> Enum.sort()

      # If a bundle file stopped being canonical it would drop off the Python
      # side's list, and the check below would silently stop covering it.
      assert Enum.sort(listed) == present
      assert length(present) == 84

      for relative <- present do
        bytes = @fixtures |> Path.join("proof/#{relative}") |> File.read!()

        assert Canonical.encode!(Jason.decode!(bytes)) == bytes,
               "#{relative} does not re-encode to its own bytes"
      end
    end

    test "every number is spelled the way the Python encoder spells it" do
      cases = @canonical |> Path.join("numbers.json") |> File.read!() |> Jason.decode!()

      assert length(cases) > 1000

      for %{"source" => source, "expected" => expected} <- cases do
        assert Canonical.encode!(Jason.decode!(source)) == expected,
               "#{source} is not spelled #{expected}"
      end
    end
  end

  describe "the three rules two implementations can differ on" do
    test "members are ordered by their UTF-16 code units, not their UTF-8 bytes" do
      # U+10000 is one UTF-16 surrogate pair beginning D800, and four UTF-8
      # bytes beginning F0. U+FFFD is EF BF BD in UTF-8. Sorting the UTF-8
      # bytes puts U+10000 last; sorting the UTF-16 code units puts it first,
      # which is the order RFC 8785 fixes.
      high = "\u{10000}"
      lower = "\u{FFFD}"

      assert {:ok, ~s({"#{high}":2,"#{lower}":1})} ==
               Canonical.encode(%{lower => 1, high => 2})
    end

    test "only the quote, the backslash and the control characters are escaped" do
      assert {:ok, ~s("a/b\\u0000\\b\\t\\n\\f\\r\\u001f\\"\\\\é😀")} =
               Canonical.encode("a/b\0\b\t\n\f\r\x1f\"\\\x7fé😀")
    end

    test "a number is spelled as the double it is, whatever it was written as" do
      assert {:ok, "1"} = Canonical.encode(1.0)
      assert {:ok, "1"} = Canonical.encode(1)
      assert {:ok, "0"} = Canonical.encode(-0.0)
      assert {:ok, "100000000000000000000"} = Canonical.encode(1.0e20)
      assert {:ok, "1e+21"} = Canonical.encode(1.0e21)
      assert {:ok, "0.000001"} = Canonical.encode(1.0e-6)
      assert {:ok, "1e-7"} = Canonical.encode(1.0e-7)
    end
  end

  describe "a value with no canonical form" do
    test "is refused rather than guessed at" do
      assert {:error, :unrepresentable_number} = Canonical.encode(Integer.pow(10, 400))
      assert {:error, :unsupported_value} = Canonical.encode(%{1 => "a"})
      assert {:error, :unsupported_value} = Canonical.encode(~D[2026-08-27])
      assert {:error, :unsupported_value} = Canonical.encode(:atom)
    end
  end
end
